-- mysqlds2_create_db.sql: DVD Store Database Version 2.1 Build Script - MySQL version
-- Copyright (C) 2005 Dell, Inc. <dave_jaffe@dell.com> and <tmuirhead@vmware.com>
-- Last updated 5/13/05


-- Database

DROP DATABASE IF EXISTS DS2;
CREATE DATABASE DS2;
USE DS2;


-- Tables

CREATE TABLE CUSTOMERS
  (
  CUSTOMERID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  FIRSTNAME VARCHAR(50) NOT NULL, 
  LASTNAME VARCHAR(50) NOT NULL, 
  ADDRESS1 VARCHAR(50) NOT NULL, 
  ADDRESS2 VARCHAR(50), 
  CITY VARCHAR(50) NOT NULL, 
  STATE VARCHAR(50), 
  ZIP INT, 
  COUNTRY VARCHAR(50) NOT NULL, 
  REGION TINYINT NOT NULL,
  EMAIL VARCHAR(50),
  PHONE VARCHAR(50),
  CREDITCARDTYPE INT NOT NULL,
  CREDITCARD VARCHAR(50) NOT NULL, 
  CREDITCARDEXPIRATION VARCHAR(50) NOT NULL, 
  USERNAME VARCHAR(50) NOT NULL, 
  PASSWORD VARCHAR(50) NOT NULL, 
  AGE TINYINT, 
  INCOME INT,
  GENDER VARCHAR(1) 
  )
  ;
  
CREATE TABLE CUST_HIST
  (
  CUSTOMERID INT NOT NULL, 
  ORDERID INT NOT NULL, 
  PROD_ID INT NOT NULL 
  )
  ;
  
CREATE TABLE ORDERS
  (
  ORDERID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  ORDERDATE DATE NOT NULL, 
  CUSTOMERID INT, 
  NETAMOUNT NUMERIC(12,2) NOT NULL, 
  TAX NUMERIC(12,2) NOT NULL, 
  TOTALAMOUNT NUMERIC(12,2) NOT NULL
  )
  ; 
  
CREATE TABLE ORDERLINES
  (
  ORDERLINEID SMALLINT NOT NULL, 
  ORDERID INT NOT NULL, 
  PROD_ID INT NOT NULL, 
  QUANTITY SMALLINT NOT NULL, 
  ORDERDATE DATE NOT NULL
  )
  ; 
  
CREATE TABLE PRODUCTS
  (
  PROD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  CATEGORY TINYINT NOT NULL, 
  TITLE VARCHAR(50) NOT NULL, 
  ACTOR VARCHAR(50) NOT NULL, 
  PRICE NUMERIC(12,2) NOT NULL, 
  SPECIAL TINYINT,
  COMMON_PROD_ID INT NOT NULL 
  )
  ;

CREATE TABLE INVENTORY
  (
  PROD_ID INT NOT NULL PRIMARY KEY,
  QUAN_IN_STOCK INT NOT NULL,
  SALES INT NOT NULL
  )
  ;
   

CREATE TABLE CATEGORIES
  (
  CATEGORY TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  CATEGORYNAME VARCHAR(50) NOT NULL  
  )
  ;
   
  
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (1,'Action');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (2,'Animation');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (3,'Children');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (4,'Classics');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (5,'Comedy');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (6,'Documentary');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (7,'Drama');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (8,'Family');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (9,'Foreign');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (10,'Games');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (11,'Horror');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (12,'Music');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (13,'New');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (14,'Sci-Fi');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (15,'Sports');
  INSERT INTO CATEGORIES (CATEGORY, CATEGORYNAME) VALUES (16,'Travel');
  

CREATE TABLE REORDER
  (
  PROD_ID INT NOT NULL,
  DATE_LOW DATE NOT NULL,
  QUAN_LOW INT NOT NULL,
  DATE_REORDERED DATE,
  QUAN_REORDERED INT,
  DATE_EXPECTED DATE
  )
  ;


-- mysqlds2_create_ind.sql: DVD Store Database Version 2.1 Create Indexes Script - MySQL version
-- Copyright (C) 2005 Dell, Inc. <dave_jaffe@dell.com> and <tmuirhead@vmware.com>
-- Last updated 5/13/05


USE DS2;

CREATE UNIQUE INDEX IX_CUST_USERNAME ON CUSTOMERS 
  (
  USERNAME
  );

CREATE INDEX IX_CUST_HIST_CUSTOMERID ON CUST_HIST
  (
  CUSTOMERID
  );

ALTER TABLE CUST_HIST
  ADD CONSTRAINT FK_CUST_HIST_CUSTOMERID FOREIGN KEY (CUSTOMERID)
  REFERENCES CUSTOMERS (CUSTOMERID)
  ON DELETE CASCADE
  ;

CREATE INDEX IX_ORDER_CUSTID ON ORDERS
  (
  CUSTOMERID
  );

ALTER TABLE ORDERS 
  ADD CONSTRAINT FK_CUSTOMERID FOREIGN KEY (CUSTOMERID)
  REFERENCES CUSTOMERS (CUSTOMERID)
  ON DELETE SET NULL
  ;

CREATE UNIQUE INDEX IX_ORDERLINES_ORDERID ON ORDERLINES
  (
  ORDERID, ORDERLINEID
  );

ALTER TABLE ORDERLINES
  ADD CONSTRAINT FK_ORDERID FOREIGN KEY (ORDERID)
  REFERENCES ORDERS (ORDERID)
  ON DELETE CASCADE
  ;

CREATE FULLTEXT INDEX IX_PROD_ACTOR ON PRODUCTS 
  (
  ACTOR
  );

CREATE INDEX IX_PROD_CATEGORY ON PRODUCTS 
  (
  CATEGORY
  );

CREATE FULLTEXT INDEX IX_PROD_TITLE ON PRODUCTS 
  (
  TITLE
  );

CREATE INDEX IX_PROD_SPECIAL ON PRODUCTS 
  (
  SPECIAL
  );

-- mysqlds2_create_sp.sql: DVD Store Database Version 2.1 Create Stored Procedures Script - MySQL version
-- Copyright (C) 2005 Dell, Inc. <dave_jaffe@dell.com> and <tmuirhead@vmware.com>
-- Last updated 5/13/05

Delimiter $
DROP PROCEDURE IF EXISTS DS2.NEW_CUSTOMER $
CREATE PROCEDURE DS2.NEW_CUSTOMER ( IN firstname_in varchar(50), IN lastname_in varchar(50), IN address1_in varchar(50), IN address2_in varchar(50), IN city_in varchar(50), IN state_in varchar(50), IN zip_in int, IN country_in varchar(50), IN region_in int, IN email_in varchar(50), IN phone_in varchar(50), IN creditcardtype_in int, IN creditcard_in varchar(50), IN creditcardexpiration_in varchar(50), IN username_in varchar(50), IN password_in varchar(50), IN age_in int, IN income_in int, IN gender_in varchar(1), OUT customerid_out INT)
  BEGIN
  DECLARE rows_returned INT;
  SELECT COUNT(*) INTO rows_returned FROM CUSTOMERS WHERE USERNAME = username_in;
  IF rows_returned = 0 
  THEN
    INSERT INTO CUSTOMERS
      (
      FIRSTNAME,
      LASTNAME,
      EMAIL,
      PHONE,
      USERNAME,
      PASSWORD,
      ADDRESS1,
      ADDRESS2,
      CITY,
      STATE,
      ZIP,
      COUNTRY,
      REGION,
      CREDITCARDTYPE,
      CREDITCARD,
      CREDITCARDEXPIRATION,
      AGE,
      INCOME,
      GENDER
      )
    VALUES
      (
      firstname_in,
      lastname_in,
      email_in,
      phone_in,
      username_in,
      password_in,
      address1_in,
      address2_in,
      city_in,
      state_in,
      zip_in,
      country_in,
      region_in,
      creditcardtype_in,
      creditcard_in,
      creditcardexpiration_in,
      age_in,
      income_in,
      gender_in
      )
      ;
    select last_insert_id() into customerid_out;
  ELSE SET customerid_out = 0;
  END IF;
  END; $

SET UNIQUE_CHECKS=0;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE CUSTOMERS DISABLE KEYS;

LOAD DATA LOCAL INFILE "data_files/cust/us_cust.csv" INTO TABLE CUSTOMERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/cust/row_cust.csv" INTO TABLE CUSTOMERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE CUSTOMERS ENABLE KEYS;

ALTER TABLE ORDERS DISABLE KEYS;

LOAD DATA LOCAL INFILE "data_files/orders/jan_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/feb_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/mar_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/apr_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/may_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/jun_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/jul_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/aug_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/sep_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/oct_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/nov_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/dec_orders.csv" INTO TABLE ORDERS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE ORDERS ENABLE KEYS;

ALTER TABLE ORDERLINES DISABLE KEYS;

LOAD DATA LOCAL INFILE "data_files/orders/jan_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/feb_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/mar_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/apr_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/may_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/jun_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/jul_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/aug_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/sep_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/oct_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/nov_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/dec_orderlines.csv" INTO TABLE ORDERLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE ORDERLINES ENABLE KEYS;

ALTER TABLE CUST_HIST DISABLE KEYS;

LOAD DATA LOCAL INFILE "data_files/orders/jan_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/feb_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/mar_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/apr_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/may_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/jun_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/jul_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/aug_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/sep_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/oct_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/nov_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE "data_files/orders/dec_cust_hist.csv" INTO TABLE CUST_HIST FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE CUST_HIST ENABLE KEYS;

ALTER TABLE PRODUCTS DISABLE KEYS;

LOAD DATA LOCAL INFILE "data_files/prod/prod.csv" INTO TABLE PRODUCTS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE PRODUCTS ENABLE KEYS;

ALTER TABLE INVENTORY DISABLE KEYS;

LOAD DATA LOCAL INFILE "data_files/prod/inv.csv" INTO TABLE INVENTORY FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

ALTER TABLE INVENTORY ENABLE KEYS;
