trivial:
	gcc trivial.c -lOpenCL -I/usr/local/cuda-8.0/include
	# gcc trivial.c -lOpenCL -I/opt/intel/opencl-1.2-sdk-6.3.0.1904/include
	# gcc trivial.c -lOpenCL -I/opt/intel/intel-opencl-1.2-6.3.0.1904/opencl-1.2-sdk-6.3.0.1904/include

mem:
	gcc mem.c -lOpenCL -I/usr/local/cuda-8.0/include
