hello:
	f95 -o _build/hello hello.f95

case:
	f95 -o _build/case_example case_example.f95

circle:
	f95 -o _build/circle_area circle_area.f95

swap:
	f95 -o _build/swap swap.f95

nfactorial:
	f95 -o _build/nfactorial nfactorial.f95

dynamic:
	f95 -o _build/dynamic_array dynamic_array.f95

dummy:
	f95 -o _build/dummy_array dummy_array.f95

module:
	f95 -o _build/module module.f95

convert:
	f95 -o _build/convert convert.f95

class:
	f95 -o _build/class class.f95

file:
	f95 -o _build/file file.f95

read:
	f95 -o _build/read read.f95

pointer:
	f95 -o _build/pointer pointer.f95
